version: "3.8"
services:
  mysql-db:
    image: mysql:8
    container_name: dbapp
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quizdb
    ports:
      - "3306:3306"
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql

  tomcat-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: regapp
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    volumes:
      - ./webapp.war:/usr/local/tomcat/webapps/webapp.war
